function(print_variable)
    message(STATUS "${ARGV0}=${${ARGV0}}")
endfunction()

function(print_env)
    message(STATUS "${ARGV0}=$ENV{${ARGV0}}")
endfunction()

if (${TARGET_ARCH} STREQUAL rh850)
    set(CMAKE_C_LINK_EXECUTABLE    "<CMAKE_C_COMPILER> <CMAKE_C_LINK_FLAGS>   <LINK_FLAGS> <OBJECTS> -o <TARGET>  <LINK_LIBRARIES>")
    SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> cr <TARGET> <LINK_FLAGS><OBJECTS>")
    list(APPEND CMAKE_ASM_SOURCE_FILE_EXTENSIONS 850 s)
endif()

function(link_directories_prepend)
    get_property(tmp_link_dir_var DIRECTORY PROPERTY LINK_DIRECTORIES)
    set(tmp_link_dir_var ${ARGV} ${tmp_link_dir_var})
    set_property(DIRECTORY PROPERTY LINK_DIRECTORIES ${tmp_link_dir_var})
endfunction()
set(CMAKE_INCLUDE_DIRECTORIES_BEFORE on)

if(DEFINED MACRO_VARIANT)
    add_definitions(-D${MACRO_VARIANT})
endif()

if (DEFINED REL_FLAGS)
    set(CMAKE_C_FLAGS_RELEASE ${REL_FLAGS})
    set(CMAKE_CXX_FLAGS_RELEASE ${REL_FLAGS})
endif()
if (DEFINED DBG_FLAGS)
    set(CMAKE_C_FLAGS_DEBUG ${DBG_FLAGS})
    set(CMAKE_CXX_FLAGS_DEBUG ${DBG_FLAGS})
endif()

if (DEFINED MACRO_DEF)
    foreach(mac ${MACRO_DEF})
        add_definitions(-D${mac})
    endforeach()
endif()

if(NOT DEFINED TOOL_ROOT)
    set(TOOL_ROOT /.)
endif()

if (DEFINED SYSTEM_ROOT)
    foreach (root ${SYSTEM_ROOT})
        file(TO_CMAKE_PATH ${root} root)
        # where is the target environment 
        set(CMAKE_FIND_ROOT_PATH ${root})

        include_directories(${root}/usr/include ${root}/include)
        link_directories(${root}/usr/lib/. ${root}/lib/.)
    endforeach()
else()
    set(SYSTEM_ROOT /.)
endif()

if (DEFINED INC_PATH)
    foreach(dir ${INC_PATH})
        file(TO_CMAKE_PATH ${dir} dir)
        include_directories(${dir}/.)
    endforeach()
endif()

if (DEFINED LIB_PATH)
    foreach(dir ${LIB_PATH})
        file(TO_CMAKE_PATH ${dir} dir)
        link_directories(${dir}/.)
    endforeach()
endif()

if(NOT DEFINED PROJECT_ROOT)
    message(FATAL_ERROR "Project Root is not defined. Please set environment variable PROOT.")
endif()
file(TO_CMAKE_PATH ${PROJECT_ROOT} PROJECT_ROOT)
set(WORKSPACE_ROOT ${PROJECT_ROOT}/workspace)

set(PROJECT_SYSROOT ${PROJECT_ROOT}/project/projroot)
set(PROJECT_EXTERNAL_ROOT ${PROJECT_ROOT}/external)
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
    if(DEFINED MACRO_VARIANT)
        set(CMAKE_INSTALL_PREFIX ${PROJECT_ROOT}/output/${MACRO_VARIANT}/${TARGET_ARCH})
    else()
        set(CMAKE_INSTALL_PREFIX ${PROJECT_ROOT}/output/${TARGET_ARCH})
    endif()
endif()

file(TO_CMAKE_PATH ${RULE_DIR} RULE_DIR)
# uninstall target
configure_file(
    "${RULE_DIR}/cmake_uninstall.cmake.in"
    "${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake"
    IMMEDIATE @ONLY)

add_custom_target(uninstall
    COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_BINARY_DIR}/cmake_uninstall.cmake)

message(STATUS "=========================configuration=========================")
print_variable(TOOL_ROOT)
print_variable(SYSTEM_ROOT)
print_variable(INSTALL_ROOT)
print_variable(COMPILER_TYPE)
print_variable(TARGET_ARCH)
print_variable(TARGET_OS)
print_variable(CMAKE_CROSSCOMPILING)
print_variable(CMAKE_C_FLAGS)
print_variable(CMAKE_CXX_FLAGS)
print_variable(REL_FLAGS)
print_variable(DBG_FLAGS)
print_variable(MACRO_DEF)
print_variable(CMAKE_SHARED_LINKER_FLAGS)
print_variable(CMAKE_EXE_LINKER_FLAGS)
print_variable(LIB_PATH)
print_variable(INC_PATH)
print_variable(PROJECT_SYSROOT)
print_variable(PROJECT_EXTERNAL_ROOT)
print_variable(CMAKE_AR)
print_variable(CMAKE_C_COMPILER)
print_variable(CMAKE_CXX_COMPILER)
print_variable(CMAKE_INSTALL_PREFIX)
message(STATUS "===============================================================")

function(target_create_executable)
    set(dummy_file ${RULE_DIR}/dummy.c)
    add_executable(${ARGV0} ${dummy_file})
endfunction()

function(target_create_library)
    set(dummy_file ${RULE_DIR}/dummy.c)
    add_library(${ARGV0} ${ARGV1} ${dummy_file})
endfunction()

function(target_source_files)
    set(srcs ${ARGV})
    list(REMOVE_AT srcs 0) 
    target_sources(${ARGV0} PRIVATE ${srcs}) 
endfunction()

macro (generate_glob_list)
    foreach(prefix *.c *.cpp *.cxx *.cc ${CMAKE_C_SOURCE_FILE_EXTENSIONS} ${CMAKE_CXX_SOURCE_FILE_EXTENSIONS} ${CMAKE_ASM_SOURCE_FILE_EXTENSIONS})
        list(APPEND ${ARGV0} ${ARGV1}/*.${prefix})
    endforeach()
endmacro()

# Usage: add_executable_from_dirs(target GLOB|GLOB_RECURSE dir1 dir2 ...)
function(target_source_directories)
    set(dirs ${ARGV})
    list(REMOVE_AT dirs 0 1) 
    foreach(dir ${dirs})
        generate_glob_list(glob_list ${dir})
        file(${ARGV1} src_list LIST_DIRECTORIES false ${glob_list})
        target_source_files(${ARGV0} ${src_list})
    endforeach()
endfunction()

