SET(CMAKE_SYSTEM_NAME Generic)

#set(CMAKE_INCLUDE_DIRECTORIES_BEFORE on)
#if(${TARGET_ARCH} STREQUAL host)
#    return()
#endif()

if(DEFINED ENV{C_COMPILER})
    SET(CMAKE_C_COMPILER $ENV{C_COMPILER})
endif()

if(DEFINED ENV{CXX_COMPILER})
    SET(CMAKE_CXX_COMPILER $ENV{CXX_COMPILER})
endif()

set(CMAKE_C_LINK_EXECUTABLE    "<CMAKE_C_COMPILER> <CMAKE_C_LINK_FLAGS>   <LINK_FLAGS> <OBJECTS> -o <TARGET>  <LINK_LIBRARIES>")
SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> cr <TARGET> <LINK_FLAGS><OBJECTS>")
list(APPEND CMAKE_ASM_SOURCE_FILE_EXTENSIONS 850 s)

# search for programs in the build host directories
#SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
# for libraries and headers in the target directories
#SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
